// GENERATED by tools/gen_firmware_header.py - do not edit.
// Source of truth: ros2_ws/src/hexapod_gait/hexapod_gait/robot_config.py
//
// Re-run the generator after any geometry change. `--check` fails when this
// file is stale, which is what CI or a pre-flight script should call.
#pragma once

#include <stdint.h>

namespace robot {

// --- Link lengths, metres, axis to axis ---------------------------------
constexpr float COXA  = 0.025000f;
constexpr float FEMUR = 0.059000f;
constexpr float TIBIA = 0.109000f;

// --- Posture and gait ---------------------------------------------------
constexpr float STAND_HEIGHT = 0.081000f;
constexpr float REACH        = 0.102000f;
constexpr float STEP_HEIGHT  = 0.038000f;
constexpr float CYCLE_TIME   = 0.900000f;

// --- Servo travel -------------------------------------------------------
// Joint angle at which each servo sits at its mechanical centre. Fit the
// horns at these angles; everything else is measured from here.
constexpr float CENTER_DEG[3] = { 0.000000f, 45.000000f, -105.000000f };
constexpr float TRAVEL_DEG    = 80.000000f;

// --- Pulse widths -------------------------------------------------------
constexpr uint16_t SERVO_MIN_US    = 500;
constexpr uint16_t SERVO_MAX_US    = 2500;
constexpr uint16_t SERVO_CENTER_US = 1500;
constexpr float    SERVO_RANGE_DEG = 180.000000f;

// --- Legs ---------------------------------------------------------------
constexpr int NUM_LEGS   = 6;
constexpr int NUM_JOINTS = 18;

struct Leg {
  const char* name;
  float mount_x, mount_y, mount_z;  // hip axis in the body frame, metres
  float yaw;                        // rest direction, radians from +X
  uint8_t group;                    // tripod: 0 or 1
};

constexpr Leg LEGS[NUM_LEGS] = {
  { "FL", 0.075000f, 0.055000f, 0.000000f, 0.785398f, 0 },   // 45 deg
  { "ML", 0.000000f, 0.070000f, 0.000000f, 1.570796f, 1 },   // 90 deg
  { "RL", -0.075000f, 0.055000f, 0.000000f, 2.356194f, 0 },   // 135 deg
  { "FR", 0.075000f, -0.055000f, 0.000000f, -0.785398f, 1 },   // -45 deg
  { "MR", 0.000000f, -0.070000f, 0.000000f, -1.570796f, 0 },   // -90 deg
  { "RR", -0.075000f, -0.055000f, 0.000000f, -2.356194f, 1 },   // -135 deg
};

// --- Servo wiring -------------------------------------------------------
// One entry per joint, in JOINT_NAMES order: leg 0 coxa/femur/tibia, then
// leg 1, and so on. `dir` is the mirror assumption and is bench-verified
// by the calibration mode, which saves any correction to NVS.
struct ServoMap {
  uint8_t board;    // 0 = PCA9685 at 0x40, 1 = at 0x41
  uint8_t channel;  // 0-15 on that board
  int8_t  dir;      // +1 or -1
};

constexpr ServoMap SERVOS[NUM_JOINTS] = {
  { 0,  0, +1 },   // FL_coxa
  { 0,  1, -1 },   // FL_femur
  { 0,  2, -1 },   // FL_tibia
  { 0,  3, +1 },   // ML_coxa
  { 0,  4, -1 },   // ML_femur
  { 0,  5, -1 },   // ML_tibia
  { 0,  6, +1 },   // RL_coxa
  { 0,  7, -1 },   // RL_femur
  { 0,  8, -1 },   // RL_tibia
  { 1,  0, +1 },   // FR_coxa
  { 1,  1, +1 },   // FR_femur
  { 1,  2, +1 },   // FR_tibia
  { 1,  3, +1 },   // MR_coxa
  { 1,  4, +1 },   // MR_femur
  { 1,  5, +1 },   // MR_tibia
  { 1,  6, +1 },   // RR_coxa
  { 1,  7, +1 },   // RR_femur
  { 1,  8, +1 },   // RR_tibia
};

constexpr const char* JOINT_NAMES[NUM_JOINTS] = {
  "FL_coxa", "FL_femur", "FL_tibia",
  "ML_coxa", "ML_femur", "ML_tibia",
  "RL_coxa", "RL_femur", "RL_tibia",
  "FR_coxa", "FR_femur", "FR_tibia",
  "MR_coxa", "MR_femur", "MR_tibia",
  "RR_coxa", "RR_femur", "RR_tibia",
};

}  // namespace robot
