#!/usr/bin/env python3
"""Generate firmware/include/robot_geometry.h from robot_config.py.

The firmware and the simulation have to agree about the robot, and the surest
way to keep them agreeing is to let neither own the numbers. `robot_config.py`
owns them; this emits the C++ view. Re-run it after any geometry change, the
same as `gen_urdf.py`.

    python tools/gen_firmware_header.py
    python tools/gen_firmware_header.py --check    # fail if the header is stale

Floats are emitted with an `f` suffix throughout: the ESP32-S3 has a
single-precision FPU, and a stray double drags the whole expression into
software emulation.
"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "ros2_ws", "src", "hexapod_gait"))
from hexapod_gait import robot_config as cfg  # noqa: E402

OUT = os.path.join(ROOT, "firmware", "include", "robot_geometry.h")


def f(x):
    return f"{x:.6f}f"


def build():
    L = []
    w = L.append
    w("// GENERATED by tools/gen_firmware_header.py - do not edit.")
    w("// Source of truth: ros2_ws/src/hexapod_gait/hexapod_gait/robot_config.py")
    w("//")
    w("// Re-run the generator after any geometry change. `--check` fails when this")
    w("// file is stale, which is what CI or a pre-flight script should call.")
    w("#pragma once")
    w("")
    w("#include <stdint.h>")
    w("")
    w("namespace robot {")
    w("")
    w("// --- Link lengths, metres, axis to axis ---------------------------------")
    w(f"constexpr float COXA  = {f(cfg.COXA)};")
    w(f"constexpr float FEMUR = {f(cfg.FEMUR)};")
    w(f"constexpr float TIBIA = {f(cfg.TIBIA)};")
    w("")
    w("// --- Posture and gait ---------------------------------------------------")
    w(f"constexpr float STAND_HEIGHT = {f(cfg.STAND_HEIGHT)};")
    w(f"constexpr float REACH        = {f(cfg.REACH)};")
    w(f"constexpr float STEP_HEIGHT  = {f(cfg.STEP_HEIGHT)};")
    w(f"constexpr float CYCLE_TIME   = {f(cfg.CYCLE_TIME)};")
    w("")
    w("// --- Servo travel -------------------------------------------------------")
    w("// Joint angle at which each servo sits at its mechanical centre. Fit the")
    w("// horns at these angles; everything else is measured from here.")
    c = cfg.JOINT_CENTER_DEG
    w(f"constexpr float CENTER_DEG[3] = {{ {f(c[0])}, {f(c[1])}, {f(c[2])} }};")
    w(f"constexpr float TRAVEL_DEG    = {f(cfg.JOINT_TRAVEL_DEG)};")
    w("")
    w("// --- Pulse widths -------------------------------------------------------")
    w(f"constexpr uint16_t SERVO_MIN_US    = {cfg.SERVO_MIN_US};")
    w(f"constexpr uint16_t SERVO_MAX_US    = {cfg.SERVO_MAX_US};")
    w(f"constexpr uint16_t SERVO_CENTER_US = {cfg.SERVO_CENTER_US};")
    w(f"constexpr float    SERVO_RANGE_DEG = {f(cfg.SERVO_RANGE_DEG)};")
    w("")
    w("// --- Legs ---------------------------------------------------------------")
    w(f"constexpr int NUM_LEGS   = {len(cfg.LEGS)};")
    w(f"constexpr int NUM_JOINTS = {len(cfg.JOINT_NAMES)};")
    w("")
    w("struct Leg {")
    w("  const char* name;")
    w("  float mount_x, mount_y, mount_z;  // hip axis in the body frame, metres")
    w("  float yaw;                        // rest direction, radians from +X")
    w("  uint8_t group;                    // tripod: 0 or 1")
    w("};")
    w("")
    w("constexpr Leg LEGS[NUM_LEGS] = {")
    import math
    for name, mount, yaw_deg, group in cfg.LEGS:
        w(f'  {{ "{name}", {f(mount[0])}, {f(mount[1])}, {f(mount[2])}, '
          f'{f(math.radians(yaw_deg))}, {group} }},   // {yaw_deg:g} deg')
    w("};")
    w("")
    w("// --- Servo wiring -------------------------------------------------------")
    w("// One entry per joint, in JOINT_NAMES order: leg 0 coxa/femur/tibia, then")
    w("// leg 1, and so on. `dir` is the mirror assumption and is bench-verified")
    w("// by the calibration mode, which saves any correction to NVS.")
    w("struct ServoMap {")
    w("  uint8_t board;    // 0 = PCA9685 at 0x40, 1 = at 0x41")
    w("  uint8_t channel;  // 0-15 on that board")
    w("  int8_t  dir;      // +1 or -1")
    w("};")
    w("")
    w("constexpr ServoMap SERVOS[NUM_JOINTS] = {")
    for i, (ch, d) in enumerate(zip(cfg.SERVO_CHANNELS, cfg.SERVO_DIR)):
        w(f"  {{ {ch // 16}, {ch % 16:2d}, {d:+d} }},   // {cfg.JOINT_NAMES[i]}")
    w("};")
    w("")
    w("constexpr const char* JOINT_NAMES[NUM_JOINTS] = {")
    for i in range(0, len(cfg.JOINT_NAMES), 3):
        row = ", ".join(f'"{n}"' for n in cfg.JOINT_NAMES[i:i + 3])
        w(f"  {row},")
    w("};")
    w("")
    w("}  // namespace robot")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated header is out of date")
    args = ap.parse_args()
    text = build()
    if args.check:
        if not os.path.exists(OUT):
            print(f"MISSING {OUT} - run tools/gen_firmware_header.py")
            return 1
        current = open(OUT, encoding="utf-8").read()
        if current != text:
            print(f"STALE {os.path.relpath(OUT, ROOT)} - "
                  "robot_config.py changed; re-run tools/gen_firmware_header.py")
            return 1
        print("robot_geometry.h is up to date")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}  "
          f"({len(cfg.JOINT_NAMES)} joints, {len(cfg.LEGS)} legs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
