#!/usr/bin/env python3
"""Generate the placeholder robot description for Gazebo from robot_config.py.

Writes into ros2_ws/src/hexapod_description/:
  urdf/hexapod_body.urdf.xacro    links and joints - the half SolidWorks (sw2urdf) replaces
  urdf/hexapod_control.xacro      ros2_control, Gazebo plugins, sensors - the half that stays
  config/controllers.yaml         controller list, joint order matching the gait node
  config/bridge.yaml              Gazebo <-> ROS topic bridge for clock, IMU and foot contacts

--check runs forward kinematics through the generated joint chain and compares
it with leg_ik.foot_position(), which catches an axis-sign mistake in the URDF
before Gazebo ever sees it. Needs only Python; run it on Windows.

Frames follow ROS (REP 103): X forward, Y left, Z up. Each leg's coxa joint
frame has +X pointing outward along the leg's rest direction, so joint angle
zero is a straight leg and the joint angles ARE the IK's angles.
"""
import argparse
import math
import os
import random
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "ros2_ws", "src", "hexapod_gait"))
from hexapod_gait import leg_ik  # noqa: E402
from hexapod_gait import robot_config as cfg  # noqa: E402

PKG = os.path.join(ROOT, "ros2_ws", "src", "hexapod_description")
WORLD = "course"
MODEL = "hexapod"
COLORS = {
    "body": "0.20 0.42 0.72 1", "coxa": "0.55 0.57 0.60 1",
    "femur": "0.85 0.45 0.15 1", "tibia": "0.75 0.78 0.82 1",
}


def fmt(v):
    return " ".join(f"{x:.5f}" for x in v)


def box_inertia(mass, x, y, z):
    return (mass / 12 * (y * y + z * z), mass / 12 * (x * x + z * z), mass / 12 * (x * x + y * y))


def inertial(mass, origin, size, extra=0.0):
    # `extra` is the servo's reflected rotor inertia, added on every axis. It
    # keeps the tensor physically valid and the solver calm - see hardware.md.
    ixx, iyy, izz = (i + extra for i in box_inertia(mass, *size))
    return (f'    <inertial>\n      <origin xyz="{fmt(origin)}"/>\n      <mass value="{mass}"/>\n'
            f'      <inertia ixx="{ixx:.3e}" iyy="{iyy:.3e}" izz="{izz:.3e}" ixy="0" ixz="0" iyz="0"/>\n'
            f'    </inertial>\n')


def link(name, size, mass, color, tibia=False):
    length = size[0]
    mid = (length / 2, 0.0, 0.0)
    out = [f'  <link name="{name}">\n']
    if tibia:
        # The foot sphere goes FIRST so sdformat names it <link>_collision,
        # which is what the contact sensor references. The shaft is a cylinder:
        # no edges to snag on a kerb (URDF has no capsule).
        out.append(f'    <collision>\n      <origin xyz="{length:.5f} 0 0"/>\n'
                   f'      <geometry><sphere radius="{cfg.FOOT_RADIUS}"/></geometry>\n    </collision>\n')
        out.append(f'    <collision>\n      <origin xyz="{fmt(mid)}" rpy="0 {math.pi / 2:.6f} 0"/>\n'
                   f'      <geometry><cylinder radius="{size[1] / 2:.4f}" length="{length - 2 * cfg.FOOT_RADIUS:.4f}"/></geometry>\n'
                   f'    </collision>\n')
    else:
        out.append(f'    <collision>\n      <origin xyz="{fmt(mid)}"/>\n'
                   f'      <geometry><box size="{fmt(size)}"/></geometry>\n    </collision>\n')
    out.append(f'    <visual>\n      <origin xyz="{fmt(mid)}"/>\n'
               f'      <geometry><box size="{fmt(size)}"/></geometry>\n'
               f'      <material name="{color}"/>\n    </visual>\n')
    out.append(inertial(mass, mid, size, cfg.SERVO_REFLECTED_INERTIA))
    out.append('  </link>\n')
    return "".join(out)


def joint(name, parent, child, xyz, rpy, axis, center_deg):
    lo = math.radians(center_deg - cfg.JOINT_TRAVEL_DEG)
    hi = math.radians(center_deg + cfg.JOINT_TRAVEL_DEG)
    return (f'  <joint name="{name}" type="revolute">\n'
            f'    <parent link="{parent}"/>\n    <child link="{child}"/>\n'
            f'    <origin xyz="{fmt(xyz)}" rpy="{fmt(rpy)}"/>\n    <axis xyz="{axis}"/>\n'
            f'    <limit lower="{lo:.4f}" upper="{hi:.4f}" effort="{cfg.SERVO_TORQUE}" velocity="{cfg.SERVO_SPEED}"/>\n'
            f'    <dynamics damping="0.01"/>\n  </joint>\n')


def body_xacro():
    out = ['<?xml version="1.0"?>\n',
           '<!-- GENERATED by tools/gen_urdf.py from hexapod_gait/robot_config.py.\n',
           '     Placeholder geometry: boxes on the real joint axes. The SolidWorks\n',
           '     export (docs/solidworks-export.md) replaces this file; keep the link\n',
           '     and joint names, hexapod_control.xacro depends on them. -->\n',
           '<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hexapod_body">\n']
    for name, rgba in COLORS.items():
        out.append(f'  <material name="{name}"><color rgba="{rgba}"/></material>\n')
    body = (cfg.BODY_LEN, cfg.BODY_WID, cfg.BODY_THK)
    out.append('  <link name="base_link">\n')
    out.append(f'    <collision><geometry><box size="{fmt(body)}"/></geometry></collision>\n')
    out.append(f'    <visual><geometry><box size="{fmt(body)}"/></geometry><material name="body"/></visual>\n')
    out.append(inertial(cfg.MASS_BODY, (0, 0, 0), body))
    out.append('  </link>\n')
    cc, cf, ct = cfg.JOINT_CENTER_DEG
    for leg, mount, yaw, _group in cfg.LEGS:
        out.append(f'\n  <!-- leg {leg} -->\n')
        out.append(joint(f"{leg}_coxa", "base_link", f"{leg}_coxa_link", mount, (0, 0, math.radians(yaw)), "0 0 1", cc))
        out.append(link(f"{leg}_coxa_link", (cfg.COXA, 0.016, 0.016), cfg.MASS_COXA, "coxa"))
        # Pitch axes are -Y so that a positive angle lifts the link, matching the IK.
        out.append(joint(f"{leg}_femur", f"{leg}_coxa_link", f"{leg}_femur_link", (cfg.COXA, 0, 0), (0, 0, 0), "0 -1 0", cf))
        out.append(link(f"{leg}_femur_link", (cfg.FEMUR, 0.014, 0.014), cfg.MASS_FEMUR, "femur"))
        out.append(joint(f"{leg}_tibia", f"{leg}_femur_link", f"{leg}_tibia_link", (cfg.FEMUR, 0, 0), (0, 0, 0), "0 -1 0", ct))
        out.append(link(f"{leg}_tibia_link", (cfg.TIBIA, 0.011, 0.011), cfg.MASS_TIBIA, "tibia", tibia=True))
    out.append('</robot>\n')
    return "".join(out)


def control_xacro():
    center = [math.radians(c) for c in cfg.JOINT_CENTER_DEG]
    out = ['<?xml version="1.0"?>\n',
           '<!-- GENERATED by tools/gen_urdf.py. ros2_control interfaces, the Gazebo\n',
           '     plugin, sensors and surface properties. Survives a SolidWorks re-export\n',
           '     as long as link and joint names are kept. -->\n',
           '<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hexapod_control">\n',
           '  <ros2_control name="GazeboSimSystem" type="system">\n',
           '    <hardware><plugin>gz_ros2_control/GazeboSimSystem</plugin></hardware>\n']
    for name in cfg.JOINT_NAMES:
        j = ("coxa", "femur", "tibia").index(name.split("_")[1])
        out.append(f'    <joint name="{name}">\n      <command_interface name="position"/>\n'
                   f'      <state_interface name="position"><param name="initial_value">{center[j]:.4f}</param></state_interface>\n'
                   f'      <state_interface name="velocity"/>\n    </joint>\n')
    out.append('  </ros2_control>\n')
    out.append('  <gazebo>\n    <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">\n'
               '      <parameters>$(find hexapod_description)/config/controllers.yaml</parameters>\n'
               '    </plugin>\n  </gazebo>\n')
    out.append('  <gazebo reference="base_link">\n    <sensor name="imu" type="imu">\n'
               '      <always_on>1</always_on>\n      <update_rate>100</update_rate>\n    </sensor>\n  </gazebo>\n')
    for leg, *_ in cfg.LEGS:
        out.append(f'  <gazebo reference="{leg}_tibia_link">\n'
                   f'    <mu1>{cfg.FOOT_FRICTION}</mu1>\n    <mu2>{cfg.FOOT_FRICTION}</mu2>\n'
                   f'    <sensor name="{leg}_foot" type="contact">\n'
                   f'      <contact><collision>{leg}_tibia_link_collision</collision></contact>\n'
                   f'      <always_on>1</always_on>\n      <update_rate>100</update_rate>\n    </sensor>\n  </gazebo>\n')
    out.append('</robot>\n')
    return "".join(out)


def controllers_yaml():
    joints = "".join(f"      - {n}\n" for n in cfg.JOINT_NAMES)
    return ("# GENERATED by tools/gen_urdf.py. Joint order here is the order of\n"
            "# /leg_controller/commands, and the gait node publishes in the same order.\n"
            "controller_manager:\n  ros__parameters:\n    update_rate: 200\n\n"
            "    joint_state_broadcaster:\n      type: joint_state_broadcaster/JointStateBroadcaster\n\n"
            "    leg_controller:\n      type: position_controllers/JointGroupPositionController\n\n"
            f"leg_controller:\n  ros__parameters:\n    joints:\n{joints}")


def bridge_yaml():
    def entry(ros, gz, ros_type, gz_type):
        return (f'- ros_topic_name: "{ros}"\n  gz_topic_name: "{gz}"\n'
                f'  ros_type_name: "{ros_type}"\n  gz_type_name: "{gz_type}"\n  direction: GZ_TO_ROS\n')
    base = f"/world/{WORLD}/model/{MODEL}/link"
    out = ["# GENERATED by tools/gen_urdf.py. Gazebo topic names follow the\n"
           "# /world/<world>/model/<model>/link/<link>/sensor/<sensor>/<type> pattern;\n"
           "# confirm with `gz topic -l` if a bridge stays silent.\n",
           entry("clock", "/clock", "rosgraph_msgs/msg/Clock", "gz.msgs.Clock"),
           entry("imu", f"{base}/base_link/sensor/imu/imu", "sensor_msgs/msg/Imu", "gz.msgs.IMU")]
    for leg, *_ in cfg.LEGS:
        out.append(entry(f"feet/{leg}", f"{base}/{leg}_tibia_link/sensor/{leg}_foot/contact",
                         "ros_gz_interfaces/msg/Contacts", "gz.msgs.Contacts"))
    return "".join(out)


# --- checks -------------------------------------------------------------------

def rot_y(v, a):
    x, y, z = v
    return (math.cos(a) * x + math.sin(a) * z, y, -math.sin(a) * x + math.cos(a) * z)


def rot_z(v, a):
    x, y, z = v
    return (math.cos(a) * x - math.sin(a) * y, math.sin(a) * x + math.cos(a) * y, z)


def chain_foot(c, f, t):
    """Foot position by walking the generated joint chain: Rz(c) coxa, Ry(-f) femur, Ry(-t) tibia."""
    p = (cfg.TIBIA, 0.0, 0.0)
    p = rot_y(p, -t)
    p = tuple(a + b for a, b in zip(p, (cfg.FEMUR, 0.0, 0.0)))
    p = rot_y(p, -f)
    p = tuple(a + b for a, b in zip(p, (cfg.COXA, 0.0, 0.0)))
    return rot_z(p, c)


def check():
    rng = random.Random(1)
    worst = 0.0
    for _ in range(2000):
        angles = (rng.uniform(-1.2, 1.2), rng.uniform(-1.0, 1.5), rng.uniform(-2.8, -0.3))
        a = chain_foot(*angles)
        b = leg_ik.foot_position(angles)
        worst = max(worst, math.dist(a, b))
    print(f"URDF chain vs leg_ik forward kinematics: worst mismatch {worst:.2e} m over 2000 poses")
    ok = worst < 1e-9

    # The stance pose must be reachable and inside every servo's travel.
    angles = leg_ik.solve(cfg.REACH, 0.0, -cfg.STAND_HEIGHT)
    foot = leg_ik.foot_position(angles)
    err = math.dist(foot, (cfg.REACH, 0.0, -cfg.STAND_HEIGHT))
    print(f"stand pose: coxa {math.degrees(angles[0]):.1f} femur {math.degrees(angles[1]):.1f} "
          f"tibia {math.degrees(angles[2]):.1f} deg, foot error {err:.1e} m, "
          f"within limits: {leg_ik.within_limits(angles)}")
    ok = ok and err < 1e-9 and leg_ik.within_limits(angles)

    # Leg rest directions: the front legs must point forward (+X) and the left legs left (+Y).
    for leg, mount, yaw, _g in cfg.LEGS:
        d = rot_z((1.0, 0.0, 0.0), math.radians(yaw))
        fwd_ok = (d[0] > 0) == (mount[0] > 0) if abs(mount[0]) > 1e-6 else abs(d[0]) < 1e-6
        left_ok = (d[1] > 0) == (mount[1] > 0)
        ok = ok and fwd_ok and left_ok
        print(f"  {leg}: mount {fmt(mount)}  points ({d[0]:+.2f}, {d[1]:+.2f})  {'ok' if fwd_ok and left_ok else 'WRONG'}")
    print("CHECK PASSED" if ok else "CHECK FAILED")
    return ok


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify the joint chain against leg_ik and exit non-zero on mismatch")
    args = ap.parse_args()
    if args.check and not check():
        sys.exit(1)
    for rel, content in (("urdf/hexapod_body.urdf.xacro", body_xacro()),
                         ("urdf/hexapod_control.xacro", control_xacro()),
                         ("config/controllers.yaml", controllers_yaml()),
                         ("config/bridge.yaml", bridge_yaml())):
        path = os.path.join(PKG, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
