#!/usr/bin/env python3
"""Compile and run the firmware's kinematics tests on this machine.

    python tools/test_firmware.py

leg_ik.h and gait.h are ports of the Python in hexapod_gait/, and a port is
exactly where a sign flips unnoticed. This regenerates the fixtures FROM the
Python, compiles the C++ against them, and runs it - so "the firmware agrees
with the simulator" is a checked fact rather than a hope.

Uses zig's C++ frontend (`pip install ziglang`), which needs no admin rights
and no Visual Studio. PlatformIO's own `pio test -e native` would do the same
job if a host toolchain is ever installed.
"""
import argparse
import io
import math
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "ros2_ws", "src", "hexapod_gait"))
from hexapod_gait import robot_config as cfg  # noqa: E402
from hexapod_gait import gait, leg_ik  # noqa: E402

FW = os.path.join(ROOT, "firmware")
FIXTURES = os.path.join(FW, "test", "fixtures.h")

IK_TARGETS = [
    (cfg.REACH, 0.0, -cfg.STAND_HEIGHT), (0.12, 0.03, -0.07),
    (0.08, -0.04, -0.09), (0.11, 0.0, -0.05), (0.06, 0.02, -0.10),
    (0.13, -0.02, -0.08), (0.09, 0.05, -0.06), (0.10, -0.05, -0.10),
]
GAIT_COMMANDS = [(0.10, 0, 0), (0, 0.08, 0), (0, 0, 1.0), (0.06, 0.03, 0.5),
                 (-0.08, 0, -0.7)]


def gen_fixtures():
    L = ["// GENERATED by tools/test_firmware.py from robot_config.py.",
         "// Every expected value here was computed by the Python reference.",
         "#pragma once", "", "struct IkCase { float x, y, z, coxa, femur, tibia; };",
         "static const IkCase IK[] = {"]
    for x, y, z in IK_TARGETS:
        a = leg_ik.solve(x, y, z)
        L.append(f"  {{ {x:.6f}f, {y:.6f}f, {z:.6f}f, "
                 f"{a[0]:.8f}f, {a[1]:.8f}f, {a[2]:.8f}f }},")
    L += ["};", "", "struct GaitCase { int leg; float vx, vy, wz, phase, ox, oy, oz; };",
          "static const GaitCase GAIT[] = {"]
    for vx, vy, wz in GAIT_COMMANDS:
        for leg_i in range(len(cfg.LEGS)):
            _name, mount, yaw_deg, group = cfg.LEGS[leg_i]
            yaw = math.radians(yaw_deg)
            neutral = (mount[0] + math.cos(yaw) * cfg.REACH,
                       mount[1] + math.sin(yaw) * cfg.REACH,
                       mount[2] - cfg.STAND_HEIGHT)
            for ph in (0.0, 0.25, 0.5, 0.75):
                o = gait.foot_offset(neutral, (vx, vy), wz, ph, group)
                L.append(f"  {{ {leg_i}, {vx:.4f}f, {vy:.4f}f, {wz:.4f}f, {ph:.4f}f, "
                         f"{o[0]:.8f}f, {o[1]:.8f}f, {o[2]:.8f}f }},")
    L += ["};", ""]
    n_ik, n_gait = len(IK_TARGETS), len(GAIT_COMMANDS) * len(cfg.LEGS) * 4
    L.append(f"constexpr int N_IK = {n_ik};")
    L.append(f"constexpr int N_GAIT = {n_gait};")
    os.makedirs(os.path.dirname(FIXTURES), exist_ok=True)
    io.open(FIXTURES, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    return n_ik, n_gait


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep", action="store_true", help="keep the built binary")
    args = ap.parse_args()

    # A stale generated header would make this test a lie.
    rc = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "gen_firmware_header.py"),
                         "--check"], capture_output=True, text=True)
    if rc.returncode != 0:
        print(rc.stdout.strip() or rc.stderr.strip())
        return 1

    n_ik, n_gait = gen_fixtures()
    print(f"fixtures: {n_ik} IK poses, {n_gait} gait samples, from the Python reference")

    out = os.path.join(FW, "test", "test_kinematics.exe" if os.name == "nt" else "test_kinematics")
    cmd = [sys.executable, "-m", "ziglang", "c++", "-std=c++17", "-O1",
           "-I", os.path.join(FW, "include"), "-I", os.path.join(FW, "test"),
           os.path.join(FW, "test", "test_kinematics.cpp"), "-o", out]
    build = subprocess.run(cmd, capture_output=True, text=True)
    if build.returncode != 0:
        print("COMPILE FAILED\n" + (build.stderr or build.stdout))
        return 1
    print("compiled with zig c++\n")

    run = subprocess.run([out], capture_output=True, text=True)
    print(run.stdout, end="")
    if run.stderr:
        print(run.stderr, end="")
    if not args.keep and os.path.exists(out):
        try:
            os.remove(out)
            for ext in (".pdb", ".obj"):
                p = out.replace(".exe", ext)
                if os.path.exists(p):
                    os.remove(p)
        except OSError:
            pass
    return run.returncode


if __name__ == "__main__":
    sys.exit(main())
